image: docker:latest

services:
  - docker:dind
  
stages:
  - build
  - test
  - release
  - deploy

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/linumlabs/proteameetup:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/linumlabs/proteameetup:latest
  
# Install docker-compose
before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - apk add --no-cache py-pip
  - pip install docker-compose

# Build master branch & push to test CR
build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - master
    
# Docker-compose setup testing
test1:
  stage: test
  script:
    - docker-compose -v
    - docker-compose build
    - docker-compose up -d

# If build passses tests, push to release CR
release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

# deploy:
#   stage: deploy
#   script:
#     - ./deploy.sh
#   only:
#     - master
