# safelist
branches:
  only:
  - master
  - docker-eb-deployment

env:
  DOCKER_COMPOSE_VERSION: 1.8.0

before_install:
  - docker-compose --version
  - docker-compose pull
  - docker-compose build
  - docker-compose start
  - docker ps