sudo: required

services:
  - docker

# safelist
branches:
  only:
  - master
  - docker-eb-deployment

before_install:
  - docker-compose --version
  - docker-compose pull
  - docker-compose build

install:
  - docker-compose up -d
  - docker ps

after_script:
  - docker ps
  - docker-compose down