apiVersion: apps/v1
kind: Deployment
metadata:
  name: proteameetup
  labels:
    app: proteameetup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proteameetup
  
  # Pod template
  template:
    metadata:
      labels:
        app: proteameetup
    spec:
      containers:
        - name: test
          image: registry.gitlab.com/linumlabs/proteameetup/protea:_TAG_
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: gitlab-registry
---
apiVersion: v1
kind: Service
metadata:
  name: proteameetup
  labels:
    app: proteameetup
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: proteameetup
