apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: _APP_NAME_
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: _APP_NAME_
    spec:
      containers:
      - name: _APP_NAME_
        image: registry.gitlab.com/linumlabs/proteameetup:_VERSION_
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: gitlab-registry
---
apiVersion: v1beta1
kind: Service
metadata:
  name: _APP_NAME_
  labels:
    app: _APP_NAME_
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: _APP_NAME_
