branch-defaults:
  master:
    environment: protea-meetup
environment-defaults:
  protea-meetup:
    branch: null
    repository: null
global:
  application_name: protea
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Docker running on
    64bit Amazon Linux/2.12.0
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli-linumlabs
  sc: git
  workspace_type: Application
